// Static beginner lesson content, keyed by language code.
//
// Each language has the same six beginner topics so the lessons browser feels
// consistent across languages. `transliteration` is left empty for Latin-script
// languages (Spanish, French, German, Italian, Portuguese) where it adds
// nothing, and filled in for languages that use a non-Latin script.

export type Phrase = {
  native: string;
  transliteration: string;
  english: string;
};

export type Lesson = {
  slug: string;
  title: string;
  description: string;
  emoji: string;
  phrases: Phrase[];
};

const p = (native: string, transliteration: string, english: string): Phrase => ({
  native,
  transliteration,
  english,
});

export const LESSONS_BY_LANGUAGE: Record<string, Lesson[]> = {
  es: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Spanish.",
      emoji: "hand",
      phrases: [
        p("Hola", "", "Hello"),
        p("Buenos días", "", "Good morning"),
        p("Buenas tardes", "", "Good afternoon"),
        p("Gracias", "", "Thank you"),
        p("Por favor", "", "Please"),
        p("Adiós", "", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("Me llamo ...", "", "My name is ..."),
        p("¿Cómo te llamas?", "", "What is your name?"),
        p("¿Cómo estás?", "", "How are you?"),
        p("Estoy bien", "", "I am fine"),
        p("Mucho gusto", "", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Spanish.",
      emoji: "numbers",
      phrases: [
        p("uno", "", "One (1)"),
        p("dos", "", "Two (2)"),
        p("tres", "", "Three (3)"),
        p("cuatro", "", "Four (4)"),
        p("cinco", "", "Five (5)"),
        p("seis", "", "Six (6)"),
        p("siete", "", "Seven (7)"),
        p("ocho", "", "Eight (8)"),
        p("nueve", "", "Nine (9)"),
        p("diez", "", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("sí", "", "Yes"),
        p("no", "", "No"),
        p("agua", "", "Water"),
        p("comida", "", "Food / meal"),
        p("bien", "", "Good / well"),
        p("grande", "", "Big"),
        p("pequeño", "", "Small"),
        p("amigo", "", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("¿Qué es esto?", "", "What is this?"),
        p("¿Cuánto cuesta?", "", "How much is it?"),
        p("No entiendo", "", "I do not understand"),
        p("Habla más despacio, por favor", "", "Please speak slowly"),
        p("Necesito ayuda", "", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("hoy", "", "Today"),
        p("mañana", "", "Tomorrow / morning"),
        p("ayer", "", "Yesterday"),
        p("tarde", "", "Afternoon / evening"),
        p("noche", "", "Night"),
        p("semana", "", "Week"),
      ],
    },
  ],
  fr: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in French.",
      emoji: "hand",
      phrases: [
        p("Bonjour", "", "Hello / good morning"),
        p("Bonsoir", "", "Good evening"),
        p("Salut", "", "Hi (informal)"),
        p("Merci", "", "Thank you"),
        p("S'il vous plaît", "", "Please"),
        p("Au revoir", "", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("Je m'appelle ...", "", "My name is ..."),
        p("Comment vous appelez-vous ?", "", "What is your name?"),
        p("Comment allez-vous ?", "", "How are you?"),
        p("Je vais bien", "", "I am fine"),
        p("Enchanté", "", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in French.",
      emoji: "numbers",
      phrases: [
        p("un", "", "One (1)"),
        p("deux", "", "Two (2)"),
        p("trois", "", "Three (3)"),
        p("quatre", "", "Four (4)"),
        p("cinq", "", "Five (5)"),
        p("six", "", "Six (6)"),
        p("sept", "", "Seven (7)"),
        p("huit", "", "Eight (8)"),
        p("neuf", "", "Nine (9)"),
        p("dix", "", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("oui", "", "Yes"),
        p("non", "", "No"),
        p("eau", "", "Water"),
        p("nourriture", "", "Food"),
        p("bien", "", "Good / well"),
        p("grand", "", "Big"),
        p("petit", "", "Small"),
        p("ami", "", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("Qu'est-ce que c'est ?", "", "What is this?"),
        p("Combien ça coûte ?", "", "How much is it?"),
        p("Je ne comprends pas", "", "I do not understand"),
        p("Parlez plus lentement, s'il vous plaît", "", "Please speak slowly"),
        p("J'ai besoin d'aide", "", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("aujourd'hui", "", "Today"),
        p("demain", "", "Tomorrow"),
        p("hier", "", "Yesterday"),
        p("matin", "", "Morning"),
        p("soir", "", "Evening"),
        p("nuit", "", "Night"),
      ],
    },
  ],
  de: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in German.",
      emoji: "hand",
      phrases: [
        p("Hallo", "", "Hello"),
        p("Guten Morgen", "", "Good morning"),
        p("Guten Tag", "", "Good day"),
        p("Danke", "", "Thank you"),
        p("Bitte", "", "Please / you're welcome"),
        p("Auf Wiedersehen", "", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("Ich heiße ...", "", "My name is ..."),
        p("Wie heißt du?", "", "What is your name?"),
        p("Wie geht es dir?", "", "How are you?"),
        p("Mir geht es gut", "", "I am fine"),
        p("Freut mich", "", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in German.",
      emoji: "numbers",
      phrases: [
        p("eins", "", "One (1)"),
        p("zwei", "", "Two (2)"),
        p("drei", "", "Three (3)"),
        p("vier", "", "Four (4)"),
        p("fünf", "", "Five (5)"),
        p("sechs", "", "Six (6)"),
        p("sieben", "", "Seven (7)"),
        p("acht", "", "Eight (8)"),
        p("neun", "", "Nine (9)"),
        p("zehn", "", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("ja", "", "Yes"),
        p("nein", "", "No"),
        p("Wasser", "", "Water"),
        p("Essen", "", "Food"),
        p("gut", "", "Good"),
        p("groß", "", "Big"),
        p("klein", "", "Small"),
        p("Freund", "", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("Was ist das?", "", "What is this?"),
        p("Wie viel kostet das?", "", "How much is it?"),
        p("Ich verstehe nicht", "", "I do not understand"),
        p("Sprechen Sie bitte langsamer", "", "Please speak slowly"),
        p("Ich brauche Hilfe", "", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("heute", "", "Today"),
        p("morgen", "", "Tomorrow"),
        p("gestern", "", "Yesterday"),
        p("Morgen", "", "Morning"),
        p("Abend", "", "Evening"),
        p("Nacht", "", "Night"),
      ],
    },
  ],
  it: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Italian.",
      emoji: "hand",
      phrases: [
        p("Ciao", "", "Hi / bye"),
        p("Buongiorno", "", "Good morning"),
        p("Buonasera", "", "Good evening"),
        p("Grazie", "", "Thank you"),
        p("Per favore", "", "Please"),
        p("Arrivederci", "", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("Mi chiamo ...", "", "My name is ..."),
        p("Come ti chiami?", "", "What is your name?"),
        p("Come stai?", "", "How are you?"),
        p("Sto bene", "", "I am fine"),
        p("Piacere", "", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Italian.",
      emoji: "numbers",
      phrases: [
        p("uno", "", "One (1)"),
        p("due", "", "Two (2)"),
        p("tre", "", "Three (3)"),
        p("quattro", "", "Four (4)"),
        p("cinque", "", "Five (5)"),
        p("sei", "", "Six (6)"),
        p("sette", "", "Seven (7)"),
        p("otto", "", "Eight (8)"),
        p("nove", "", "Nine (9)"),
        p("dieci", "", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("sì", "", "Yes"),
        p("no", "", "No"),
        p("acqua", "", "Water"),
        p("cibo", "", "Food"),
        p("bene", "", "Good / well"),
        p("grande", "", "Big"),
        p("piccolo", "", "Small"),
        p("amico", "", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("Che cos'è questo?", "", "What is this?"),
        p("Quanto costa?", "", "How much is it?"),
        p("Non capisco", "", "I do not understand"),
        p("Parla più lentamente, per favore", "", "Please speak slowly"),
        p("Ho bisogno di aiuto", "", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("oggi", "", "Today"),
        p("domani", "", "Tomorrow"),
        p("ieri", "", "Yesterday"),
        p("mattina", "", "Morning"),
        p("sera", "", "Evening"),
        p("notte", "", "Night"),
      ],
    },
  ],
  pt: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Portuguese.",
      emoji: "hand",
      phrases: [
        p("Olá", "", "Hello"),
        p("Bom dia", "", "Good morning"),
        p("Boa tarde", "", "Good afternoon"),
        p("Obrigado", "", "Thank you"),
        p("Por favor", "", "Please"),
        p("Tchau", "", "Bye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("Meu nome é ...", "", "My name is ..."),
        p("Como você se chama?", "", "What is your name?"),
        p("Como vai?", "", "How are you?"),
        p("Estou bem", "", "I am fine"),
        p("Prazer", "", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Portuguese.",
      emoji: "numbers",
      phrases: [
        p("um", "", "One (1)"),
        p("dois", "", "Two (2)"),
        p("três", "", "Three (3)"),
        p("quatro", "", "Four (4)"),
        p("cinco", "", "Five (5)"),
        p("seis", "", "Six (6)"),
        p("sete", "", "Seven (7)"),
        p("oito", "", "Eight (8)"),
        p("nove", "", "Nine (9)"),
        p("dez", "", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("sim", "", "Yes"),
        p("não", "", "No"),
        p("água", "", "Water"),
        p("comida", "", "Food"),
        p("bom", "", "Good"),
        p("grande", "", "Big"),
        p("pequeno", "", "Small"),
        p("amigo", "", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("O que é isto?", "", "What is this?"),
        p("Quanto custa?", "", "How much is it?"),
        p("Não entendo", "", "I do not understand"),
        p("Fale mais devagar, por favor", "", "Please speak slowly"),
        p("Preciso de ajuda", "", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("hoje", "", "Today"),
        p("amanhã", "", "Tomorrow"),
        p("ontem", "", "Yesterday"),
        p("manhã", "", "Morning"),
        p("noite", "", "Night / evening"),
        p("semana", "", "Week"),
      ],
    },
  ],
  zh: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Mandarin Chinese.",
      emoji: "hand",
      phrases: [
        p("你好", "nǐ hǎo", "Hello"),
        p("早上好", "zǎoshang hǎo", "Good morning"),
        p("谢谢", "xièxie", "Thank you"),
        p("请", "qǐng", "Please"),
        p("对不起", "duìbuqǐ", "Sorry"),
        p("再见", "zàijiàn", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("我叫 ...", "wǒ jiào ...", "My name is ..."),
        p("你叫什么名字？", "nǐ jiào shénme míngzi?", "What is your name?"),
        p("你好吗？", "nǐ hǎo ma?", "How are you?"),
        p("我很好", "wǒ hěn hǎo", "I am fine"),
        p("很高兴认识你", "hěn gāoxìng rènshi nǐ", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Mandarin Chinese.",
      emoji: "numbers",
      phrases: [
        p("一", "yī", "One (1)"),
        p("二", "èr", "Two (2)"),
        p("三", "sān", "Three (3)"),
        p("四", "sì", "Four (4)"),
        p("五", "wǔ", "Five (5)"),
        p("六", "liù", "Six (6)"),
        p("七", "qī", "Seven (7)"),
        p("八", "bā", "Eight (8)"),
        p("九", "jiǔ", "Nine (9)"),
        p("十", "shí", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("是", "shì", "Yes / to be"),
        p("不", "bù", "No / not"),
        p("水", "shuǐ", "Water"),
        p("饭", "fàn", "Food / rice"),
        p("好", "hǎo", "Good"),
        p("大", "dà", "Big"),
        p("小", "xiǎo", "Small"),
        p("朋友", "péngyou", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("这是什么？", "zhè shì shénme?", "What is this?"),
        p("多少钱？", "duōshao qián?", "How much is it?"),
        p("我不懂", "wǒ bù dǒng", "I do not understand"),
        p("请说慢一点", "qǐng shuō màn yìdiǎn", "Please speak slowly"),
        p("我需要帮助", "wǒ xūyào bāngzhù", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("今天", "jīntiān", "Today"),
        p("明天", "míngtiān", "Tomorrow"),
        p("昨天", "zuótiān", "Yesterday"),
        p("早上", "zǎoshang", "Morning"),
        p("晚上", "wǎnshang", "Evening"),
        p("星期", "xīngqī", "Week"),
      ],
    },
  ],
  ja: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Japanese.",
      emoji: "hand",
      phrases: [
        p("こんにちは", "konnichiwa", "Hello / good afternoon"),
        p("おはようございます", "ohayō gozaimasu", "Good morning"),
        p("ありがとう", "arigatō", "Thank you"),
        p("お願いします", "onegai shimasu", "Please"),
        p("すみません", "sumimasen", "Excuse me / sorry"),
        p("さようなら", "sayōnara", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("私の名前は ... です", "watashi no namae wa ... desu", "My name is ..."),
        p("お名前は何ですか？", "onamae wa nan desu ka?", "What is your name?"),
        p("お元気ですか？", "ogenki desu ka?", "How are you?"),
        p("元気です", "genki desu", "I am fine"),
        p("はじめまして", "hajimemashite", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Japanese.",
      emoji: "numbers",
      phrases: [
        p("一", "ichi", "One (1)"),
        p("二", "ni", "Two (2)"),
        p("三", "san", "Three (3)"),
        p("四", "shi / yon", "Four (4)"),
        p("五", "go", "Five (5)"),
        p("六", "roku", "Six (6)"),
        p("七", "shichi / nana", "Seven (7)"),
        p("八", "hachi", "Eight (8)"),
        p("九", "kyū", "Nine (9)"),
        p("十", "jū", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("はい", "hai", "Yes"),
        p("いいえ", "iie", "No"),
        p("水", "mizu", "Water"),
        p("ご飯", "gohan", "Food / rice"),
        p("いい", "ii", "Good"),
        p("大きい", "ōkii", "Big"),
        p("小さい", "chiisai", "Small"),
        p("友達", "tomodachi", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("これは何ですか？", "kore wa nan desu ka?", "What is this?"),
        p("いくらですか？", "ikura desu ka?", "How much is it?"),
        p("わかりません", "wakarimasen", "I do not understand"),
        p("ゆっくり話してください", "yukkuri hanashite kudasai", "Please speak slowly"),
        p("助けてください", "tasukete kudasai", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("今日", "kyō", "Today"),
        p("明日", "ashita", "Tomorrow"),
        p("昨日", "kinō", "Yesterday"),
        p("朝", "asa", "Morning"),
        p("夜", "yoru", "Night"),
        p("週", "shū", "Week"),
      ],
    },
  ],
  hi: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Hindi.",
      emoji: "hand",
      phrases: [
        p("नमस्ते", "namaste", "Hello"),
        p("सुप्रभात", "suprabhaat", "Good morning"),
        p("धन्यवाद", "dhanyavaad", "Thank you"),
        p("कृपया", "kripaya", "Please"),
        p("माफ़ कीजिए", "maaf kijiye", "Excuse me / sorry"),
        p("अलविदा", "alvida", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("मेरा नाम ... है", "mera naam ... hai", "My name is ..."),
        p("आपका नाम क्या है?", "aapka naam kya hai?", "What is your name?"),
        p("आप कैसे हैं?", "aap kaise hain?", "How are you?"),
        p("मैं ठीक हूँ", "main theek hoon", "I am fine"),
        p("आपसे मिलकर खुशी हुई", "aapse milkar khushi hui", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Hindi.",
      emoji: "numbers",
      phrases: [
        p("एक", "ek", "One (1)"),
        p("दो", "do", "Two (2)"),
        p("तीन", "teen", "Three (3)"),
        p("चार", "chaar", "Four (4)"),
        p("पाँच", "paanch", "Five (5)"),
        p("छह", "chhah", "Six (6)"),
        p("सात", "saat", "Seven (7)"),
        p("आठ", "aath", "Eight (8)"),
        p("नौ", "nau", "Nine (9)"),
        p("दस", "das", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("हाँ", "haan", "Yes"),
        p("नहीं", "nahin", "No"),
        p("पानी", "paani", "Water"),
        p("खाना", "khaana", "Food / meal"),
        p("अच्छा", "achha", "Good / okay"),
        p("बड़ा", "bada", "Big"),
        p("छोटा", "chhota", "Small"),
        p("दोस्त", "dost", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("यह क्या है?", "yeh kya hai?", "What is this?"),
        p("यह कितने का है?", "yeh kitne ka hai?", "How much is it?"),
        p("मुझे समझ नहीं आया", "mujhe samajh nahin aaya", "I do not understand"),
        p("कृपया धीरे बोलिए", "kripaya dheere boliye", "Please speak slowly"),
        p("मुझे मदद चाहिए", "mujhe madad chahiye", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("आज", "aaj", "Today"),
        p("कल", "kal", "Tomorrow / yesterday"),
        p("सुबह", "subah", "Morning"),
        p("शाम", "shaam", "Evening"),
        p("रात", "raat", "Night"),
        p("सप्ताह", "saptaah", "Week"),
      ],
    },
  ],
  ar: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Arabic.",
      emoji: "hand",
      phrases: [
        p("السلام عليكم", "as-salaamu alaikum", "Peace be upon you (hello)"),
        p("صباح الخير", "sabaah al-khayr", "Good morning"),
        p("شكرا", "shukran", "Thank you"),
        p("من فضلك", "min fadlik", "Please"),
        p("عفوا", "afwan", "Excuse me / you're welcome"),
        p("مع السلامة", "ma'a as-salaama", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("اسمي ...", "ismi ...", "My name is ..."),
        p("ما اسمك؟", "ma ismuk?", "What is your name?"),
        p("كيف حالك؟", "kayfa haaluk?", "How are you?"),
        p("أنا بخير", "ana bi-khayr", "I am fine"),
        p("تشرفنا", "tasharrafna", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Arabic.",
      emoji: "numbers",
      phrases: [
        p("واحد", "waahid", "One (1)"),
        p("اثنان", "ithnaan", "Two (2)"),
        p("ثلاثة", "thalaatha", "Three (3)"),
        p("أربعة", "arba'a", "Four (4)"),
        p("خمسة", "khamsa", "Five (5)"),
        p("ستة", "sitta", "Six (6)"),
        p("سبعة", "sab'a", "Seven (7)"),
        p("ثمانية", "thamaaniya", "Eight (8)"),
        p("تسعة", "tis'a", "Nine (9)"),
        p("عشرة", "ashara", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("نعم", "na'am", "Yes"),
        p("لا", "laa", "No"),
        p("ماء", "maa'", "Water"),
        p("طعام", "ta'aam", "Food"),
        p("جيد", "jayyid", "Good"),
        p("كبير", "kabeer", "Big"),
        p("صغير", "sagheer", "Small"),
        p("صديق", "sadeeq", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("ما هذا؟", "ma haadha?", "What is this?"),
        p("بكم هذا؟", "bikam haadha?", "How much is it?"),
        p("لا أفهم", "laa afham", "I do not understand"),
        p("تكلم ببطء من فضلك", "takallam bi-but' min fadlik", "Please speak slowly"),
        p("أحتاج مساعدة", "ahtaaj musaa'ada", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("اليوم", "al-yawm", "Today"),
        p("غدا", "ghadan", "Tomorrow"),
        p("أمس", "ams", "Yesterday"),
        p("صباح", "sabaah", "Morning"),
        p("مساء", "masaa'", "Evening"),
        p("ليل", "layl", "Night"),
      ],
    },
  ],
  ur: [
    {
      slug: "greetings",
      title: "Greetings & Courtesy",
      description: "The first words to greet people warmly and be polite in Urdu.",
      emoji: "hand",
      phrases: [
        p("السلام علیکم", "assalaam-o-alaikum", "Peace be upon you (hello)"),
        p("وعلیکم السلام", "wa-alaikum-assalaam", "And peace be upon you too (reply)"),
        p("آداب", "aadaab", "Respectful greeting / hello"),
        p("شکریہ", "shukriya", "Thank you"),
        p("معاف کیجیے", "maaf kijiye", "Excuse me / sorry"),
        p("خدا حافظ", "khuda haafiz", "Goodbye"),
      ],
    },
    {
      slug: "introductions",
      title: "Introducing Yourself",
      description: "Say your name, ask someone's name, and exchange basic pleasantries.",
      emoji: "person",
      phrases: [
        p("میرا نام ۔۔۔ ہے", "mera naam ... hai", "My name is ..."),
        p("آپ کا نام کیا ہے؟", "aap ka naam kya hai?", "What is your name?"),
        p("آپ کیسے ہیں؟", "aap kaise hain?", "How are you?"),
        p("میں ٹھیک ہوں", "main theek hoon", "I am fine"),
        p("آپ سے مل کر خوشی ہوئی", "aap se mil kar khushi hui", "Nice to meet you"),
      ],
    },
    {
      slug: "numbers",
      title: "Numbers 1 to 10",
      description: "Count from one to ten in Urdu.",
      emoji: "numbers",
      phrases: [
        p("ایک", "aik", "One (1)"),
        p("دو", "do", "Two (2)"),
        p("تین", "teen", "Three (3)"),
        p("چار", "chaar", "Four (4)"),
        p("پانچ", "paanch", "Five (5)"),
        p("چھ", "chhe", "Six (6)"),
        p("سات", "saat", "Seven (7)"),
        p("آٹھ", "aath", "Eight (8)"),
        p("نو", "nau", "Nine (9)"),
        p("دس", "das", "Ten (10)"),
      ],
    },
    {
      slug: "common-words",
      title: "Everyday Words",
      description: "High-frequency words you will use in almost every conversation.",
      emoji: "chat",
      phrases: [
        p("ہاں", "haan", "Yes"),
        p("نہیں", "nahin", "No"),
        p("پانی", "paani", "Water"),
        p("کھانا", "khaana", "Food / meal"),
        p("اچھا", "achha", "Good / okay"),
        p("بڑا", "bara", "Big"),
        p("چھوٹا", "chhota", "Small"),
        p("دوست", "dost", "Friend"),
      ],
    },
    {
      slug: "useful-phrases",
      title: "Useful Phrases",
      description: "Short sentences to help you get by in real situations.",
      emoji: "phrase",
      phrases: [
        p("یہ کیا ہے؟", "ye kya hai?", "What is this?"),
        p("کتنے کا ہے؟", "kitne ka hai?", "How much is it?"),
        p("مجھے سمجھ نہیں آئی", "mujhe samajh nahin aayi", "I did not understand"),
        p("براہِ کرم آہستہ بولیں", "baraah-e-karam aahista bolein", "Please speak slowly"),
        p("مدد چاہیے", "madad chahiye", "I need help"),
      ],
    },
    {
      slug: "days-time",
      title: "Days & Time",
      description: "Talk about days of the week and times of day.",
      emoji: "clock",
      phrases: [
        p("آج", "aaj", "Today"),
        p("کل", "kal", "Tomorrow / yesterday"),
        p("صبح", "subah", "Morning"),
        p("شام", "shaam", "Evening"),
        p("رات", "raat", "Night"),
        p("ہفتہ", "hafta", "Week / Saturday"),
      ],
    },
  ],
};
