// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/learning-indicator/Current.tsx": () => import("../components/mockups/learning-indicator/Current.tsx"),
  "./components/mockups/learning-indicator/GlyphAvatar.tsx": () => import("../components/mockups/learning-indicator/GlyphAvatar.tsx"),
  "./components/mockups/learning-indicator/MinimalPill.tsx": () => import("../components/mockups/learning-indicator/MinimalPill.tsx"),
  "./components/mockups/learning-indicator/NativeImmersive.tsx": () => import("../components/mockups/learning-indicator/NativeImmersive.tsx"),
  "./components/mockups/learning-indicator/ProgressBadge.tsx": () => import("../components/mockups/learning-indicator/ProgressBadge.tsx")
};
